insert into public.edital_programas (edital_catalog_id, subject_catalog_id, texto, fonte_url, conferido_em)
select e.id, s.id, v.texto, 'https://sistemas.institutoverbena.ufg.br/2024/concurso-tj-go/sistema/arquivos/editais/RL-EDITAL_TJ_ABERTURA_COMPILADO-2024.pdf', '2026-08-03'
from (values
  ('tj-go-oficial-de-justica', 'Direito Constitucional', '1. Princípios fundamentais. 2. Direitos: deveres individuais e coletivos. 3. Direitos sociais. 4. Nacionalidade e direitos políticos. 5. Organização político-administrativa. 6. União. 7. Administração Pública. 8. Servidores públicos. 9. Poder Legislativo. 10. Congresso Nacional. 11. Processo Legislativo. 12. Fiscalização contábil, financeira e orçamentária. 13. Poder Executivo. 14. Presidente e Vice-Presidente da República. 15. Poder Judiciário. 16. Funções essenciais à justiça: Ministério Público.'),
  ('tj-go-oficial-de-justica', 'Direito Administrativo', '1. Administração Pública: características. 2. Modo de atuação. 3. Regime Jurídico. 4. Personalidade Jurídica do Estado, Órgãos e Agentes. 5. Serviços públicos. 6. Responsabilidade. 7. Controle da Administração. 8. Princípios Constitucionais da Administração Pública. 9. Poderes Administrativos: vinculado, discricionário, hierárquico, disciplinar, regulamentar e de polícia. 10. Atos Administrativos: conceitos, requisitos, atributos, discricionariedade e vinculação. 11. Classificação. 12. Espécies. 13. Anulação e revogação. 14. Servidores Públicos. 15. Processo Administrativo no âmbito da Administração Pública Federal (Lei nº 9.784/1999 e alterações posteriores). 16. Licitações e Contratos Administrativos: Lei nº 8.666/93 e suas alterações na Lei nº 14.133/2021.'),
  ('tj-go-oficial-de-justica', 'Direito Civil', '1. Doutrina: conceito de lei; vigência e aplicação da lei no tempo e no espaço; integração e interpretação da lei. 2. Código Civil: das pessoas (pessoas naturais). 3. Pessoas Jurídicas: pessoas jurídicas de direito público e de direito privado. 4. Domicílio Civil. 5. Dos fatos jurídicos: do negócio jurídico, requisitos de validade do negócio jurídico, dos atos jurídicos (lícitos e dos atos ilícitos). 6. Requisitos de validade do ato jurídico. 7. Ato nulo e ato anulável. 8. Da prescrição e decadência. 9. Do Direito das Obrigações. 10. Dos contratos em geral. 11. Da prestação de serviço. 12. Da empreitada. 13. Do mandado. 14. Do mandato judicial. 15. Responsabilidade civil.'),
  ('tj-go-oficial-de-justica', 'Direito Processual Civil', '1. Código de Processo Civil: noções de jurisdição e da ação. 2. Das partes e dos procuradores. 3. Do Ministério Público. 4. Do Juiz. 5. Dos atos processuais. 6. Da formação, da suspensão e da extinção do processo. 7. Do Processo e do procedimento: das disposições gerais. 8. Da antecipação dos efeitos da tutela de mérito. 9. Do Procedimento ordinário: da petição inicial. 10. Da resposta do réu. 11. Do julgamento conforme o estado do processo. 12. Das provas. 13. Da audiência. 14. Da revelia. 15. Da sentença e a coisa julgada. 16. Dos recursos. 17. Do processo de execução. 18. Do processo cautelar. 19. Da impenhorabilidade do Bem de Família (Lei nº 8.009/1990).'),
  ('tj-go-oficial-de-justica', 'Direito Penal', '1. Crime e contravenção. 2. Elementos do crime. 3. Relação de causalidade. 4. Crime tentado e crime consumado. 5. Dolo e culpa. 6. Causas de exclusão de culpabilidade. 7. Erro. 8. Coação irresistível. 9. Obediência hierárquica. 10. Crimes contra a Administração Pública. 11. Atos de improbidade praticados por agentes públicos e sanções aplicáveis. 12. Efeitos da condenação penal. 13. Crime de responsabilidade fiscal (Lei nº 10.028/2000). 14. Crimes de responsabilidade (Lei nº 1.079/1950 e Decreto lei nº 201/1967).'),
  ('tj-go-oficial-de-justica', 'Direito Processual Penal', '1. Aplicação da lei processual no tempo, no espaço e em relação às pessoas. 2. Sujeitos da relação processual. 3. Ação penal: conceito, condições e pressupostos processuais. 4. Ação penal pública: titularidade e condições de procedibilidade. 5. Ação penal privada: titularidade. 6. Extinção da punibilidade. 7. Forma, lugar e tempo dos atos processuais. 8. Da sentença: requisitos, classificação, publicação e intimação, efeitos civis da sentença penal. 9. Das nulidades. 10. Dos recursos: modalidades e princípio da fungibilidade. 11. Do processo e do julgamento dos crimes de responsabilidade dos funcionários públicos')
) as v(slug, materia, texto)
join public.editais_catalog e on e.slug = v.slug
join public.subjects_catalog s on s.name = v.materia
on conflict (edital_catalog_id, subject_catalog_id) do update
  set texto = excluded.texto, fonte_url = excluded.fonte_url, conferido_em = excluded.conferido_em;

insert into public.edital_programas (edital_catalog_id, subject_catalog_id, texto, fonte_url, conferido_em)
select e.id, s.id, v.texto, 'https://sistemas.institutoverbena.ufg.br/2024/concurso-tj-go/sistema/arquivos/editais/RL-EDITAL_TJ_ABERTURA_COMPILADO-2024.pdf', '2026-08-03'
from (values
  ('tj-go-oficial-de-justica', 'Informática', '1. Família de sistemas operacionais Microsoft Windows para microcomputadores pessoais: interface gráfica do usuário e seus elementos, além da utilização da ajuda e suporte e dos atalhos de teclado. 2. Gerenciamento de arquivos e pastas, incluindo os tipos de arquivos e suas extensões e a pesquisa e localização de conteúdo. 3. Configurações e Painel de Controle, abrangendo a Solução de Problemas. 4. Procedimentos de backup e gerenciamento de impressão. 5. Instalação, desinstalação ou alteração de programas e ativação ou desativação de recursos, incluindo a configuração de aplicativos. 6. Compactação e extração de conteúdo a partir de arquivos zip. 7. Aplicativos pertencentes ao Windows (Bloco de Notas, Paint, WordPad e Mapa de Caracteres). 8. Aplicativos para escritórios por meio de software livre e de software proprietário. 9. Processador de textos (criação, edição e formatação de textos e recursos voltados à automação de documentos). 10. Planilha eletrônica (tipos de dados e referências, criação de planilhas e gráficos, inserindo fórmulas aritméticas e fórmulas baseadas em funções de planilha, configuração de página e impressão, formatação de células e formatação condicional, validação de dados e aplicação de filtros e obtenção de dados de fontes externas. 11. Gerador de apresentação (criação de slides, formatação e inserção de imagens e objetos e efeitos de transição e animações, apresentação de slides e exportação para o formato PDF). 12. Navegadores de Internet, serviços de busca na Web e uso do correio eletrônico. 13. Serviços de correio eletrônico.')
) as v(slug, materia, texto)
join public.editais_catalog e on e.slug = v.slug
join public.subjects_catalog s on s.name = v.materia
on conflict (edital_catalog_id, subject_catalog_id) do update
  set texto = excluded.texto, fonte_url = excluded.fonte_url, conferido_em = excluded.conferido_em;

do $$
declare v int;
begin
  select count(*) into v from public.edital_programas ep
  join public.editais_catalog e on e.id = ep.edital_catalog_id
  where e.slug = 'tj-go-oficial-de-justica';
  if v <> 11 then raise exception 'esperado 11 linhas de programa (5 comuns + 6 novas), achei %', v; end if;
end $$;
