-- Programa oficial por (edital, matéria) — P1 do diagnóstico de 03/08.
-- `topicos_curados` é um booleano sem lastro: afirma que a lista de tópicos
-- foi conferida, mas não guarda CONTRA O QUÊ. Esta tabela guarda o texto
-- verbatim do conteúdo programático oficial (Anexo II), com fonte e data:
--   - o aluno confere o programa oficial na própria página do edital;
--   - retificação vira diff de texto, não re-curadoria do zero;
--   - o mapeamento item→tópico (fase 2 do P1) nasce por cima disto.
-- Texto extraído por script dos mesmos PDFs oficiais da curadoria
-- (pdftotext -raw, Anexos II retificados de 12/05/2022) — não digitado à mão.
-- QOS 2º Tenente (médicos, Edital 003) fora: cargos não existem no catálogo.

create table public.edital_programas (
  edital_catalog_id  uuid not null references public.editais_catalog(id) on delete cascade,
  subject_catalog_id uuid not null references public.subjects_catalog(id) on delete cascade,
  texto        text not null,
  fonte_url    text,
  conferido_em date,
  primary key (edital_catalog_id, subject_catalog_id)
);

comment on table public.edital_programas is
  'Conteúdo programático oficial (verbatim do edital/anexo) por matéria. Fonte da verdade da curadoria de tópicos por edital.';

alter table public.edital_programas enable row level security;
create policy "catalog_read_edital_programas" on public.edital_programas
  for select to authenticated using (true);
create policy "read edital_programas anon" on public.edital_programas
  for select to anon using (true);

insert into public.edital_programas (edital_catalog_id, subject_catalog_id, texto, fonte_url, conferido_em)
select e.id, s.id, v.texto, v.fonte_url, '2026-08-03'
from (values
  ('pm-go-soldado', 'Língua Portuguesa', '1. Compreensão e interpretação de texto. 2. Tipologia e gêneros textuais. 3. Figuras de linguagem. 4. Significação de palavras e expressões. 5. Relações de sinonímia e de antonímia. 6. Ortografia. 7. Acentuação gráfica. 8. Uso da crase. 9. Morfologia: classes de palavras variáveis e invariáveis e seus empregos no texto. 10. Locuções verbais (perífrases verbais). 11. Funções do "que" e do "se". 12. Elementos de comunicação e funções da linguagem. 13. Domínio dos mecanismos de coesão textual: emprego de elementos de referenciação, substituição e repetição, de conectores e de outros elementos de sequenciação textual; emprego de tempos e modos verbais. 14. Domínio dos mecanismos de coerência textual. 15. Reescrita de frases e parágrafos do texto: significação das palavras; substituição de palavras ou de trechos de texto; reorganização da estrutura de orações e de períodos do texto; reescrita de textos de diferentes gêneros e níveis de formalidade. 16. Sintaxe: relações sintático-semânticas estabelecidas na oração e entre orações, períodos ou parágrafos (período simples e período composto por coordenação e subordinação). 17. Concordância verbal e nominal. 18. Regência verbal e nominal. 19. Colocação pronominal. 20. Emprego dos sinais de pontuação e sua função no texto. 21. Função textual dos vocábulos. Variação linguística. 22. Redação Oficial.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Conhecimentos Regionais', '1. Formação econômica de Goiás: a mineração no século XVIII, a agropecuária nos séculos XIX e XX, a estrada de ferro e a modernização da economia goiana, as transformações econômicas com a construção de Goiânia e Brasília, industrialização, infraestrutura e planejamento. 2. Aspectos físicos do território goiano: vegetação, hidrografia, clima e relevo. 3. Aspectos da história política de Goiás: os bandeirantes e a colonização, o coronelismo e oligarquia na República Velha, a Revolução de 1930, aspectos políticos e administrativos de 1930 até os dias atuais. 4. Aspectos da História Sociocultural de Goiás: o povoamento branco, os grupos indígenas, a escravidão e cultura negra, os movimentos sociais no campo e a cultura popular goiana. 5. Atualidades econômicas, políticas, sociais e culturais do Brasil do Estado de Goiás.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Penal', 'Direito Penal: 1. Aplicação da lei penal. 1.1. Princípios da legalidade e da anterioridade. 1.2 A lei penal no tempo e no espaço. 1.3 Tempo e lugar do crime. 1.4. Lei penal excepcional, especial e temporária. 1.5. Territorialidade e extraterritorialidade da lei penal. 1.6. Pena cumprida no estrangeiro. 1.7. Eficácia da sentença estrangeira. 1.8. Contagem de prazo. 1.9. Frações não computáveis da pena. 1.10. Interpretação da lei penal. 1.11. Analogia. 1.12. Irretroatividade da lei penal. 1.13. Conflito aparente de normas penais. 2. Crimes contra a pessoa. 3. Crimes contra o patrimônio. 4. Crimes contra a administração pública. 5. Disposições constitucionais aplicáveis ao direito penal. 6. Lei Maria da Penha (Lei federal nº 11.340/2006, arts. 01a 07).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Constitucional', '1. Dos princípios fundamentais. 1.1. Dos direitos e garantias fundamentais (direitos e deveres individuais e coletivos, nacionalidade). 1.2. Da organização do Estado (organização político-administrativa, União, Estados Federados, Municípios, Distrito Federal e Territórios, militares dos Estados, Distrito Federal e Territórios). 1.3. Da organização dos poderes (poder legislativo, congresso nacional, atribuições do congresso nacional, câmara dos deputados, senado federal, deputados e senadores, processo legislativo, poder executivo). 1.4. Da defesa do Estado e das Instituições Democráticas (estado de defesa e estado de sítio, Forças Armadas, segurança pública). 1.5. Da administração pública.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Processual Penal', '1. Aplicação da lei processual no tempo, no espaço e em relação às pessoas. 1.1. Disposições preliminares do Código de Processo Penal. 2. Inquérito policial. 3. Ação penal. 4. Prisão, medidas cautelares e liberdade provisória. 4.1. Lei federal nº 7.960/1989 (prisão temporária). 5. Processo e julgamento dos crimes de responsabilidade dos funcionários públicos. 6. O habeas corpus e seu processo. 7. Jurisdição e competência. 8. Das questões e processos incidentes. 9. Da prova. 10. Do processo comum. 11. Das nulidades e dos recursos.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Administrativo', '1. Estado, governo e administração pública: conceitos, elementos, poderes e organização; natureza, fins e princípios. 2. Organização administrativa do Estado; administração direta e indireta. 3. Agentes públicos: espécies e classificação; poderes, deveres e prerrogativas; cargo, emprego e função públicos; regime jurídico único: provimento, vacância, remoção, redistribuição e substituição; direitos e vantagens; regime disciplinar; responsabilidade civil, criminal e administrativa. 4. Poderes administrativos: poder hierárquico; poder disciplinar; poder regulamentar; poder de polícia; uso e abuso do poder. 5. Atos administrativos: conceitos, requisitos, atributos, classificação, espécies e invalidação. 6. Controle e responsabilização da administração: controle administrativo; controle judicial; controle legislativo; responsabilidade civil do Estado. 7. Lei federal nº 8.429/1992 (Dispõe sobre as sanções aplicáveis em virtude da prática de atos de improbidade administrativa). 8. Leis de licitação 8.666/93 e 14.133/2021. 9. Lei Estadual nº 13.800 (Regula o processo administrativo no âmbito da Administração Pública do Estado de Goiás).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Penal Militar', '1. Decreto-Lei 1.001/69. 1.1. Aplicação da lei penal militar. 1.2. Do Crime. 1.3. Da Imputabilidade Penal. 1.4. Concurso de agentes. 1.5. Das penas principais. 1.6. Das Penas acessórias. 1.7. Efeitos da condenação. 1.8. Ação penal. 1.9. Extinção da punibilidade. 1.10. Dos crimes militares em tempo de paz (arts. 136 ao 354). 1.11. Dos crimes contra a autoridade ou disciplina militar. 1.12. Dos crimes contra o serviço e o dever militar. 1.13. Dos crimes contra a Administração Militar. 1.11. Dos crimes militares em tempo de guerra (arts. 355 ao 408).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Direito Processual Penal Militar', 'Decreto-Lei 1002/69. Da Lei processual penal militar e sua aplicação. Da polícia judiciária militar. Da ação penal militar. Do juiz, auxiliares e partes no processo. Da denúncia. Do foro militar. Da competência, desaforamento e dos conflitos de competência. Das questões prejudiciais. Dos incidentes. Das medidas preventivas e assecuratórias. Das comunicações processuais. Das provas. Dos processos. Das nulidades e dos recursos. Da execução. Da justiça militar em tempo de Guerra. Do inquérito policial militar.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado', 'Legislação Penal Especial', '1. Tráfico ilícito e uso indevido de drogas (Lei nº 11.343/2006). 2. Crimes hediondos (Lei nº 8.072/1990).3. Crimes resultantes de preconceitos de raça ou de cor (Lei nº 7.716/1989). 4. Abuso de Autoridade (Lei nº 13.869/2019). 5. Crimes de tortura (Lei nº 9.455/1997). 6. Estatuto da Criança e do Adolescente (Lei nº 8.069/1990). 7. Estatuto do desarmamento (Lei nº 10.826/2003). 8. Crimes previstos no Código de proteção e defesa do consumidor (Lei nº 8.078/1990). 9. Crimes contra o meio ambiente (Lei nº 9.605/1998). 10. Juizados especiais (Lei nº 9.099/1995 e Lei nº 10.259/2001). 11. Crimes previstos no Código de Trânsito Brasileiro (Lei nº 9.503/1997). 12. Interceptação telefônica (Lei nº 9.296/1996). 13. Lei nº 12.850/2013. 14. Pacote Anticrime (Lei nº 13.964/2019).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Língua Portuguesa', '1. Compreensão e interpretação de texto. 2. Tipologia e gêneros textuais. 3. Figuras de linguagem. 4. Significação de palavras e expressões. 5. Relações de sinonímia e de antonímia. 6. Ortografia. 7. Acentuação gráfica. 8. Uso da crase. 9. Morfologia: classes de palavras variáveis e invariáveis e seus empregos no texto. 10. Locuções verbais (perífrases verbais). 11. Funções do "que" e do "se". 12. Elementos de comunicação e funções da linguagem. 13. Domínio dos mecanismos de coesão textual: emprego de elementos de referenciação, substituição e repetição, de conectores e de outros elementos de sequenciação textual; emprego de tempos e modos verbais. 14. Domínio dos mecanismos de coerência textual. 15. Reescrita de frases e parágrafos do texto: significação das palavras; substituição de palavras ou de trechos de texto; reorganização da estrutura de orações e de períodos do texto; reescrita de textos de diferentes gêneros e níveis de formalidade. 16. Sintaxe: relações sintático-semânticas estabelecidas na oração e entre orações, períodos ou parágrafos (período simples e período composto por coordenação e subordinação). 17. Concordância verbal e nominal. 18. Regência verbal e nominal. 19. Colocação pronominal. 20. Emprego dos sinais de pontuação e sua função no texto. 21. Função textual dos vocábulos. Variação linguística. 22. Redação Oficial.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Conhecimentos Regionais', '1. Formação econômica de Goiás: a mineração no século XVIII, a agropecuária nos séculos XIX e XX, a estrada de ferro e a modernização da economia goiana, as transformações econômicas com a construção de Goiânia e Brasília, industrialização, infraestrutura e planejamento. 2. Aspectos físicos do território goiano: vegetação, hidrografia, clima e relevo. 3. Aspectos da história política de Goiás: os bandeirantes e a colonização, o coronelismo e oligarquia na República Velha, a Revolução de 1930, aspectos políticos e administrativos de 1930 até os dias atuais. 4. Aspectos da História Sociocultural de Goiás: o povoamento branco, os grupos indígenas, a escravidão e cultura negra, os movimentos sociais no campo e a cultura popular goiana. 5. Atualidades econômicas, políticas, sociais e culturais do Brasil do Estado de Goiás.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Direito Constitucional', '1. Constituição. 1.1. Conceito, classificações, princípios fundamentais. 2. Direitos e garantias fundamentais. 2.1. Direitos e deveres individuais e coletivos, direitos sociais, nacionalidade, cidadania, direitos políticos, partidos políticos. 3. Organização político-administrativa. 3.1. União, estados, Distrito Federal, municípios e territórios. 4. Administração pública. 4.1. Disposições gerais, servidores públicos. 5. Poder Legislativo: composição. 6. Poder Executivo: forma e sistema de governo; chefia de Estado e chefia de Governo. 7. Defesa do Estado e das instituições democráticas: segurança pública; organização da segurança pública. 8. Poder judiciário: disposições gerais. 9. Anistia e Indulto: generalidades e competência.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Direito Administrativo', '1. Estado, governo e administração pública: conceitos, elementos, poderes e organização; natureza, fins e princípios. 2. Organização administrativa do Estado; administração direta e indireta. 3. Agentes públicos: espécies e classificação; poderes, deveres e prerrogativas; cargo, emprego e função públicos; regime jurídico único: provimento, vacância, remoção, redistribuição e substituição; direitos e vantagens; regime disciplinar; responsabilidade civil, criminal e administrativa. 4. Poderes administrativos: poder hierárquico; poder disciplinar; poder regulamentar; poder de polícia; uso e abuso do poder. 5. Atos administrativos: conceitos, requisitos, atributos, classificação, espécies e invalidação. 6. Controle e responsabilização da administração: controle administrativo; controle judicial; controle legislativo; responsabilidade civil do Estado. 7. Lei federal nº 8.429/1992 (Dispõe sobre as sanções aplicáveis em virtude da prática de atos de improbidade administrativa). 8. Leis de licitação 8.666/93 e 14.133/2021. 9. Lei Estadual nº 13.800 (Regula o processo administrativo no âmbito da Administração Pública do Estado de Goiás).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Direito Penal Militar', 'Decreto-Lei 1.001/69. 1.1. Aplicação da lei penal militar. 1.2. Do Crime. 1.3. Da Imputabilidade Penal. 1.4. Concurso de agentes. 1.5. Das penas. 1.6. Das Penas acessórias. 1.7. Efeitos da condenação. 1.8. Ação penal. 1.9. Extinção da punibilidade. 1.10. Dos crimes militares em tempo de paz (arts. 136 ao 354). 1.11. Dos crimes militares em tempo de guerra (arts. 355 ao 408).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-soldado-musico', 'Teoria Musical', '1. Conteúdo Teoria Geral Da Música. 2. Construção e análise de escalas em geral. 3. Ornamentos. 4. Transposição e instrumentos transpositores. 5. Tons vizinhos e modulação. 6. Análise harmônica em graus e cifras; tríades e tétrades em estado fundamental e inversões. 7. Identificação da função das notas de tensão: nota de passagem, apojatura, retardo, antecipação e bordadura. 8. Compasso simples composto e misto. 9. Análise fraseológica: semi frases, frases, períodos, seções, cadência de frases ­ autêntica, plagau, enganosa e meia cadência.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-fd3.pdf'),
  ('pm-go-oficial', 'Língua Portuguesa', '1. Compreensão e interpretação de texto. 2. Tipologia e gêneros textuais. 3. Figuras de linguagem. 4. Significação de palavras e expressões. 5. Relações de sinonímia e de antonímia. 6. Ortografia. 7. Acentuação gráfica. 8. Uso da crase. 9. Morfologia: classes de palavras variáveis e invariáveis e seus empregos no texto. 10. Locuções verbais (perífrases verbais). 11. Funções do "que" e do "se". 12. Elementos de comunicação e funções da linguagem. 13. Domínio dos mecanismos de coesão textual: emprego de elementos de referenciação, substituição e repetição, de conectores e de outros elementos de sequenciação textual; emprego de tempos e modos verbais. 14. Domínio dos mecanismos de coerência textual. 15. Reescrita de frases e parágrafos do texto: significação das palavras; substituição de palavras ou de trechos de texto; reorganização da estrutura de orações e de períodos do texto; reescrita de textos de diferentes gêneros e níveis de formalidade. 16. Sintaxe: relações sintático-semânticas estabelecidas na oração e entre orações, períodos ou parágrafos (período simples e período composto por coordenação e subordinação). 17. Concordância verbal e nominal. 18. Regência verbal e nominal. 19. Colocação pronominal. 20. Emprego dos sinais de pontuação e sua função no texto. 21. Função textual dos vocábulos. Variação linguística. 22. Redação Oficial.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Conhecimentos Regionais', '1. Formação econômica de Goiás: a mineração no século XVIII, a agropecuária nos séculos XIX e XX, a estrada de ferro e a modernização da economia goiana, as transformações econômicas com a construção de Goiânia e Brasília, industrialização, infraestrutura e planejamento. 2. Aspectos físicos do território goiano: vegetação, hidrografia, clima e relevo. 3. Aspectos da história política de Goiás: os bandeirantes e a colonização, o coronelismo e oligarquia na República Velha, a Revolução de 1930, aspectos políticos e administrativos de 1930 até os dias atuais. 4. Aspectos da História Sociocultural de Goiás: o povoamento branco, os grupos indígenas, a escravidão e cultura negra, os movimentos sociais no campo e a cultura popular goiana. 5. Atualidades econômicas, políticas, sociais e culturais do Brasil do Estado de Goiás.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Penal', '1. Da Aplicação da Lei Penal (arts. 1º ao 12 do C.P.). 2. Do Crime (arts. 13 a 25 do C.P.). 3. Da Imputabilidade penal (arts. 26 a 28 do C.P.). 4. Do Concurso de pessoas (arts. 29 a 31 do C.P.). 5. Das Penas e sua Aplicação (arts. 32 a 76 do C.P.). 6. Suspensão condicional da pena (arts. 77 a 82 do C.P.) e Livramento condicional (arts. 83 a 90 do C.P.). 7. Dos Efeitos da condenação: Reabilitação e medidas de segurança (arts. 91 a 99 do C.P.). 8. Da Ação Penal (arts. 100 a 106 do C.P.). 9. Da Extinção da punibilidade (arts. 107 a 120 do C. P.). 10. Dos Crimes contra a pessoa e contra o patrimônio (arts. 121 a 183 do C.P.). 11. Dos Crimes contra a dignidade sexual Dos Crimes contra os costumes (arts. 213 a 234-B do C.P.) e contra a família (arts. 235 a 249 do C.P.). 12. Dos Crimes contra a incolumidade pública (arts. 250 a 285 do C.P.) e contra a fé pública (arts. 289 a 311 do C.P.). 13. Dos Crimes contra a Administração Pública (arts. 312 a 359-H do C.P.). 14. Decreto-Lei nº 3.688/41 (Contravenções Penais) e Legislação Penal Especial. 15. Lei Nº 13.869, de 5 de setembro de 2019 (Crimes de Abuso de autoridade). 16. Lei 7.960/89. 17. Decreto-Lei 201/67 (Crimes de Responsabilidade de Prefeitos e Vereadores). 18. Lei 5.250/67 (Crimes de imprensa), com as alterações dadas pelas Leis 6.071/74, 6.640/79 e 7.300/85. 19. Lei 6.766/79 (Crimes definidos na Lei de parcelamento do solo urbano). 20. Lei 8.137/90 (Crimes contra a ordem tributária) e alterações. 21. Lei Nº 12.850, de 2 de agosto de 2013 (Crime organizado). 22. Leis: 9.303/96 e 10.217/01. 23. Lei 9.296/96 (Crime de interceptação e de comunicação telefônica). 24. Lei 9.455/97 (Crimes de tortura). 25. Lei 10.741/03. 26. Leis 9.985/00 e 11.204/06. 27. Lei 9.613/98 (Lavagem de dinheiro), com as alterações dadas pelas Leis 10.467/02 e 10.701/03. 28. Lei 11.101/2005 (Crimes falimentares). Lei 11.340/2006 (violência familiar e doméstica contra a mulher).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Constitucional', '1. Direito Constitucional. 1.1. Poder constituinte. 1.2. Natureza. 1.3. Poder constituinte originário. 1.4. Poder constituinte derivado. 1.5. Limites ao poder de reforma da Constituição. 1.6. Conceito e Espécies. 1.7. Cláusulas pétreas. 1.8. Normas constitucionais. 1.9. Classificação. 1.10. Interpretação, integração e aplicação. 1.11. Controle da constitucionalidade. 1.12. Via de ação e via de exceção. 1.13. Controle de constitucionalidade por omissão. 1.14. Recepção. 1.15. Repristinação. 1.16. Princípios fundamentais da Constituição (arts. 1º a 4º). 1.17. Direitos e deveres individuais e coletivos (art. 5º). 1.18. Direitos sociais. 1.19. Nacionalidade. 1.20. Direitos políticos (arts. 6º a 16º). 1.21. Organização do Estado. 1.22. Organização administrativa. 1.23. União. Estados. 1.24. Distrito Federal. 1.25. Municípios. 1.26. Intervenção nos Estados e Municípios (arts. 18 a 36). 1.27. Da Organização dos Poderes. 1.28. Poder Legislativo. 1.29. Estrutura e competência (arts. 44 a 52 e 59 a 69). 1.30. Poder Executivo. 1.31. Estrutura e competência (arts. 76 a 86). 1.32. Poder Judiciário. 1.33. Estrutura e competência (arts. 92 a 125). 1.34. Das funções essenciais à Justiça: Ministério Público (arts. 127 a 132). 1.35. Advocacia e Defensoria Pública (arts. 133 a 135). 1.36. Da ordem econômica e financeira: Princípios gerais (arts. 170 a 181). 1.37. Política agrícola e fundiária e reforma agrária (arts. 184 a 191). 1.38. Sistema financeiro nacional (art. 192). 1.39. Ordem social: Saúde (arts. 196 a 200). 1.40. Comunicação social (arts. 220 a 224). 1.41. Meio ambiente (art. 225). 1.42. Família: Criança, adolescente e idosos (arts. 226 a 230). 1.43. Constituição do Estado de Goiás - Da Organização dos Poderes, Estruturas e Competência.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Processual Penal', '1. Direito Processual Penal: Aplicação da lei processual no tempo, no espaço e em relação às pessoas. 1.1. Disposições preliminares do Código de Processo Penal. 2. Inquérito policial (arts. 4º a 23 do C.P.P.). 3. Ação penal (arts. 24 a 62 do C.P.P.). 4. Competência (arts. 69 a 91 do C.P.P.). 5. Questões e Processos Incidentes (arts. 92 a 154 do C.P.P.). 6. Prova (arts. 155 a 250 do C.P.P.). 7. Do Juiz, do Ministério Público, do Acusado e Defensor, dos Assistentes e Auxiliares da Justiça (arts. 251 a 281 do C.P.P.). 8. Prisão e Liberdade Provisória (arts. 282 a 350 do C.P.P.). 9. Citações e Intimações (arts. 351 a 372 do C.P.P.). 10. Sentença (arts. 381 a 393 do C.P.P.). 11. Processos em Espécie (arts. 394 a 555 do C.P.P.). 12. Nulidades (arts. 563 a 573 do C.P.P.). 13. Recursos (arts. 574 a 620 do C.P.P.). 14. Revisão Criminal (arts. 621 a 631 do C.P.P.). 15. Habeas Corpus (arts. 647 a 667 do C.P.P.) e Mandado de Segurança em Matéria Penal. 16. Lei 7.210/84 (Execução Penal). 17. Lei 11.340/2006 (violência familiar e doméstica contra a mulher). 18. Lei nº 9.099/95 e 10.259/2001, com as alterações das Leis 9.839/99, 10.455/02 e 11.313/06 (Juizados Especiais Criminais). 19. Lei federal nº 7.960/1989 (prisão temporária).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Administrativo', '1. Administração Pública: conceito, elementos, natureza e objetivos. Organização Administrativa do Estado: Administração direta e indireta; Agentes Públicos: espécie e classificação, poderes, deveres e prerrogativas; cargo, emprego. 2. Atividade administrativa: abuso e desvio de poder, desvio de finalidade. 3. Administração Pública: princípios da legalidade, moralidade, impessoalidade, proporcionalidade, eficiência, continuidade e autoexecutoriedade. 4. Os poderes administrativos: regulamentar, hierárquico, disciplinar e de polícia. 5. A discricionariedade, conteúdo e limites. 6. Autarquias, fundações, empresas públicas e sociedades de economia mista. 7. A privatização, disciplina e efeitos. O serviço público: concessão, autorização e permissão. 8. Agências reguladoras. 9. Ato administrativo: conceitos, requisitos, atributos, classificação, espécie e invalidação 10. Condições e pressupostos. 11. Vícios. 12. Formas de desconstituição, revogação e anulação. 13. Contrato administrativo: características, formalização, execução, inexecução e principais tipos. 14. Formas de rescisão e revisão. 15. Equilíbrio contratual e cláusulas exorbitantes. 16. Leis de licitação 8.666/93 e 14.133/2021. 17. Dispensa e inexigibilidade. 18. O procedimento licitatório. 19. Direito de propriedade e limitações administrativas. 20. A desapropriação e seu processo. 21. Requisição, servidão e ocupação provisória. 22. O controle da Administração e suas modalidades. 23. Mandado de segurança, ação popular e ação civil pública. 24. A responsabilidade civil do Estado pelos atos executivos, legislativos e jurisdicionais. 25. O processo administrativo, finalidades, garantias e tipos. Lei Estadual nº 13.800 (Regula o processo administrativo no âmbito da Administração Pública do Estado de Goiás). 26. Servidores públicos: direitos, deveres e responsabilidades. 27. Lei nº 8.429/1992 ­ Dispõe sobre as sanções aplicáveis em virtude da prática de atos de improbidade administrativa.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Penal Militar', '1. Decreto-Lei 1.001/69. 1.1. Da aplicação da Lei penal militar. 1.2. Do crime. 1.3. Da imputabilidade penal. 1.4. Do concurso de agentes. 1.5. Das penas. 1.6. Efeitos da condenação. 1.7. Das medidas de segurança. 1.8. Da ação penal. 1.9. Da extinção da punibilidade. 1.10. Dos crimes militares em tempo de paz (arts. 136 ao 354). 1.11. Dos crimes militares em tempo de guerra (arts. 355 ao 408). Dos crimes contra a administração militar.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Direito Processual Penal Militar', '1. Decreto-Lei 1.002/69. 1.1. Da Lei processual penal militar e sua aplicação. 1.2. Da polícia judiciária militar. 1.3. Da ação penal militar. 1.4. Do juiz, auxiliares e partes no processo. 1.5. Da denúncia. 1.6. Do foro militar. 1.7. Da competência, desaforamento e dos conflitos de competência. 1.8. Das questões prejudiciais. 1.9. Dos incidentes. 1.10. Dos crimes contra a autoridade ou disciplina militar. 1.11. Dos crimes contra o serviço e o dever militar. 1.12. Das medidas preventivas e assecuratórias. 1.13. Dos processos. 1.14. Das nulidades e dos recursos. 1.15. Da execução. 1.16. Da justiça militar em tempo de Guerra. 1.17. Do Inquérito Policial Militar. 1.18. Da citação, intimação e notificação. 1.19. Dos atos probatórios.', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf'),
  ('pm-go-oficial', 'Legislação Penal Especial', '1. Estatuto do Desarmamento (Lei nº 10.826/03). 2. Crimes hediondos (Lei nº 8.072/90). 3. Crimes resultantes de preconceitos de raça ou de cor (Lei nº 7.716/89). 4. Apresentação e uso de documento de identificação pessoal (Lei nº 5.553/68). 5. Lei 13. 869/2019- Dispõe sobre os crimes de abuso de autoridade. 6. Definição dos crimes de tortura (Lei nº 9.455/97). 7. Estatuto da Criança e do Adolescente (Lei nº 8.069/90). 8. Estatuto do Idoso (Lei nº 10.741/03): dos crimes em espécies. 9. Código de Trânsito Brasileiro (Lei nº 9.503/97).10. Lei Maria da Penha ­ Violência doméstica e familiar contra a mulher (Lei nº 11.340/06): Título I e II, Cap. III do Título III. 11. Sistema Nacional de Políticas Públicas sobre Drogas (Lei nº 11.343/06). 12. Crimes contra as Relações de Consumo (Título II da Lei nº 8.078/90). 13. Lei das Contravenções Penais (Decreto-Lei nº 3.688/41). 14. Lei dos Crimes contra o Meio Ambiente (Lei nº 9.605/98). 15. Estatuto dos Policiais Militares do Estado de Goiás (Lei Estadual n.º 8.033/75).', 'https://goias.gov.br/administracao/wp-content/uploads/sites/27/2022/04/120522-AnexoIIRetificado-88e.pdf')
) as v(slug, materia, texto, fonte_url)
join public.editais_catalog e on e.slug = v.slug
join public.subjects_catalog s on s.name = v.materia
on conflict (edital_catalog_id, subject_catalog_id) do update
  set texto = excluded.texto, fonte_url = excluded.fonte_url, conferido_em = excluded.conferido_em;

-- Verificação dura: 24 seções (9+6+9) e nenhum programa de matéria que o
-- edital não tenha na grade.
do $$
declare v int;
begin
  select count(*) into v from public.edital_programas;
  if v <> 24 then raise exception 'edital_programas: esperado 24, achei %', v; end if;
  select count(*) into v from public.edital_programas p
  where not exists (
    select 1 from public.edital_catalog_subjects ecs
    where ecs.edital_catalog_id = p.edital_catalog_id
      and ecs.subject_catalog_id = p.subject_catalog_id
  );
  if v > 0 then raise exception 'programa órfão (matéria fora da grade): %', v; end if;
end $$;
